### ISSUE TITLE
Code Injection vulnerability found in js-yaml dependency

### ISSUE THREAD

**Issue by SilentComics** [tachyons-css/cli#24]
``` tachyons-cli > tachyons-build-css > cssnano > postcss-svgo > svgo > js-yaml```

To remediate:

Upgrade js-yaml to version 3.13.1 or later
[https://npmjs.com/advisories/813 ](https://npmjs.com/advisories/813) 

Thank you!

**Comment by YJPL** [comment]
This shouldn't happen if you install globally

```npm install --global tachyons-cli```

see: https://github.com/tachyons-css/cli#installation

> It is meant to be installed globally with the --global flag, and requires v4 of node or higher.

If you get this error, uninstall  tachyons-cli [dev]:  

```npm uninstall tachyons-cli```

then use the global installation command, to install the package properly. That will suppress the warning(s).

**Comment by SilentComics** [comment]
Exactly. Oversight on my part. Reinstalled globally and it works without warning anymore. Thanks.
